### ISSUE TITLE
Amsterdam won't start if path contains utf-8

### ISSUE THREAD

**Issue by regit** [StamusNetworks/Amsterdam#11]
All is in the subject.

**Comment by regit** [comment]
To reproduce:
- create directory with accentuation
- export LANG=C
- from that directory run setup
- then run start

**Comment by regit** [comment]
Traceback is:

```
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.5.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 54, in main
    command.sys_dispatch()
  File "/usr/lib/python2.7/dist-packages/compose/cli/docopt_command.py", line 23, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/lib/python2.7/dist-packages/compose/cli/docopt_command.py", line 26, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 169, in perform_command
    project = project_from_options(self.base_dir, options)
  File "/usr/lib/python2.7/dist-packages/compose/cli/command.py", line 54, in project_from_options
    network_driver=options.get('--x-network-driver'),
  File "/usr/lib/python2.7/dist-packages/compose/cli/command.py", line 90, in get_project
    config.load(config_details),
  File "/usr/lib/python2.7/dist-packages/compose/config/config.py", line 227, in load
    return build_services(config_file)
  File "/usr/lib/python2.7/dist-packages/compose/config/config.py", line 208, in build_services
    for name, service_dict in config_file.config.items()
  File "/usr/lib/python2.7/dist-packages/compose/config/config.py", line 201, in build_service
    validate_paths(service_dict)
  File "/usr/lib/python2.7/dist-packages/compose/config/config.py", line 530, in validate_paths
    if not os.path.exists(build_path) or not os.access(build_path, os.R_OK):
  File "/usr/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 29: ordinal not in range(128)
```
