### ISSUE TITLE
Setup fails - API conflict on 16.04

### ISSUE THREAD

**Issue by francoisbegin** [StamusNetworks/Amsterdam#40]
On a clean install of 16.04, following installation instructions, I get a conflict between client API and server API.

root@ubuntu1604VM:/home/fbegin1# docker -v
Docker version 1.11.2, build b9f10c9

root@ubuntu1604VM:/home/fbegin1# amsterdam -d ams -i enp0s3 setup
Traceback (most recent call last):
  File "/usr/local/bin/amsterdam", line 46, in <module>
    ams = Amsterdam(args.name, args.iface, basepath)
  File "/usr/local/lib/python2.7/dist-packages/amsterdam/amsterdam.py", line 47, in **init**
    self.check_environment()
  File "/usr/local/lib/python2.7/dist-packages/amsterdam/amsterdam.py", line 119, in check_environment
    self.api_version = Client().version()['ApiVersion']
  File "/usr/local/lib/python2.7/dist-packages/docker/api/daemon.py", line 76, in version
    return self._result(self._get(url), json=True)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 178, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 174, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("client is newer than server (client API version: 1.24, server API version: 1.23)")

**Comment by francoisbegin** [comment]
More details -- docker version does not show this conflict:

root@ubuntu1604VM:/home/fbegin1# docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Thu, 16 Jun 2016 21:17:51 +1200
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Thu, 16 Jun 2016 21:17:51 +1200
 OS/Arch:      linux/amd64

**Comment by francoisbegin** [comment]
Hum... Another case of Ubuntu being great for stability but not so much for keeping up with projects that iterate quickly. Solved the issue by purging the official Docker package and instead installing the latest Docker with 
wget -qO- https://get.docker.com/ | sh
