### ISSUE TITLE
Error installing from setup

### ISSUE THREAD

**Issue by michaelseto** [StamusNetworks/Amsterdam#44]
[admin@myserver Amsterdam-master]$ amsterdam -d ams -i eth0 setup
Traceback (most recent call last):
  File "/usr/bin/amsterdam", line 4, in <module>
    __import__('pkg_resources').run_script('amsterdam==1.2', 'amsterdam')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/amsterdam-1.2-py2.7.egg/EGG-INFO/scripts/amsterdam", line 46, in <module>
    ams = Amsterdam(args.name, args.iface, basepath)
  File "/usr/lib/python2.7/site-packages/amsterdam-1.2-py2.7.egg/amsterdam/amsterdam.py", line 58, in __init__
    self.check_environment()
  File "/usr/lib/python2.7/site-packages/amsterdam-1.2-py2.7.egg/amsterdam/amsterdam.py", line 140, in check_environment
    self.get_api_version()
  File "/usr/lib/python2.7/site-packages/amsterdam-1.2-py2.7.egg/amsterdam/amsterdam.py", line 123, in get_api_version
    self.api_version = Client().version()['ApiVersion']
  File "/usr/lib/python2.7/site-packages/docker/api/daemon.py", line 76, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 139, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(2, 'No such file or directory'))

**Comment by pevma** [comment]
What OS is that on ?

**Comment by regit** [comment]
Looks like you don't have the right to talk to docker as admin user.
